# Generated by Django 5.1.1 on 2025-12-29 18:46

import icssmrProject.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('qualification', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=200)),
                ('address1', models.TextField()),
                ('address2', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pin', models.CharField(max_length=10)),
                ('marks_10', models.DecimalField(decimal_places=2, max_digits=5)),
                ('marks_12', models.DecimalField(decimal_places=2, max_digits=5)),
                ('marks_ug', models.DecimalField(decimal_places=2, max_digits=5)),
                ('marks_pg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ug_marksheet', models.FileField(upload_to=icssmrProject.models.student_upload_path)),
                ('x_admit', models.FileField(upload_to=icssmrProject.models.student_upload_path)),
                ('x_marksheet', models.FileField(upload_to=icssmrProject.models.student_upload_path)),
                ('xii_marksheet', models.FileField(upload_to=icssmrProject.models.student_upload_path)),
                ('aadhar', models.FileField(upload_to=icssmrProject.models.student_upload_path)),
                ('cv', models.FileField(upload_to=icssmrProject.models.student_upload_path)),
                ('photo', models.ImageField(upload_to=icssmrProject.models.student_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
