# Generated by Django 5.1.1 on 2025-12-31 18:12

import icssmrProject.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icssmrProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociateMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('organization', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('experience', models.PositiveIntegerField()),
                ('sector', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=300)),
                ('address2', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pin', models.CharField(max_length=10)),
                ('aadhar', models.FileField(upload_to=icssmrProject.models.associate_upload_path)),
                ('office_id', models.FileField(upload_to=icssmrProject.models.associate_upload_path)),
                ('cv', models.FileField(upload_to=icssmrProject.models.associate_upload_path)),
                ('photo', models.ImageField(upload_to=icssmrProject.models.associate_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BulkMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
