# Generated by Django 5.1.1 on 2025-12-31 19:25

import icssmrProject.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icssmrProject', '0002_associatemembership_bulkmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('institution', models.CharField(max_length=200)),
                ('experience', models.PositiveIntegerField()),
                ('designation', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=50)),
                ('specialization', models.TextField()),
                ('research_interest', models.TextField()),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=10)),
                ('aadhar', models.FileField(upload_to=icssmrProject.models.faculty_upload_path)),
                ('id_card', models.FileField(upload_to=icssmrProject.models.faculty_upload_path)),
                ('cv', models.FileField(upload_to=icssmrProject.models.faculty_upload_path)),
                ('photo', models.ImageField(upload_to=icssmrProject.models.faculty_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
