# Generated by Django 5.1.1 on 2026-01-01 08:12

import icssmrProject.models
import icssmrProject.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icssmrProject', '0003_facultymembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('address1', models.TextField()),
                ('address2', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pin', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=50)),
                ('marks10', models.DecimalField(decimal_places=2, max_digits=5)),
                ('marks12', models.DecimalField(decimal_places=2, max_digits=5)),
                ('marksUG', models.DecimalField(decimal_places=2, max_digits=5)),
                ('marksPG', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('internship', models.CharField(max_length=10)),
                ('domain', models.CharField(blank=True, max_length=200, null=True)),
                ('aadhar', models.FileField(upload_to=icssmrProject.utils.student_upload_path)),
                ('collegeid', models.FileField(upload_to=icssmrProject.utils.student_upload_path)),
                ('cv', models.FileField(upload_to=icssmrProject.utils.student_upload_path)),
                ('photo', models.ImageField(upload_to=icssmrProject.utils.student_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='aadhar',
            field=models.FileField(upload_to=icssmrProject.models.student_upload_path),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='cv',
            field=models.FileField(upload_to=icssmrProject.models.student_upload_path),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='photo',
            field=models.ImageField(upload_to=icssmrProject.models.student_upload_path),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='ug_marksheet',
            field=models.FileField(upload_to=icssmrProject.models.student_upload_path),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='x_admit',
            field=models.FileField(upload_to=icssmrProject.models.student_upload_path),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='x_marksheet',
            field=models.FileField(upload_to=icssmrProject.models.student_upload_path),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='xii_marksheet',
            field=models.FileField(upload_to=icssmrProject.models.student_upload_path),
        ),
    ]
