# Generated by Django 5.1.1 on 2026-01-01 08:14

import icssmrProject.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icssmrProject', '0006_alter_studentregistration_aadhar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='aadhar',
            field=models.FileField(upload_to=icssmrProject.models.student_upload_path),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='cv',
            field=models.FileField(upload_to=icssmrProject.models.student_upload_path),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='photo',
            field=models.ImageField(upload_to=icssmrProject.models.student_upload_path),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='ug_marksheet',
            field=models.FileField(upload_to=icssmrProject.models.student_upload_path),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='x_admit',
            field=models.FileField(upload_to=icssmrProject.models.student_upload_path),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='x_marksheet',
            field=models.FileField(upload_to=icssmrProject.models.student_upload_path),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='xii_marksheet',
            field=models.FileField(upload_to=icssmrProject.models.student_upload_path),
        ),
    ]
